# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
     inputs:
      Url:
        description: 'Url'     
        required: true
        default: 'https://preview-ng.labstar.com/'
      Username:
        description: 'Username'     
        required: true
        default: 'support'
      Password:
        description: 'Password'     
        required: true
        default: 'eVxU6%wK9'

env:
  LABSTAR-URL: ${{ github.event.inputs.Url }}
  LABSTAR-USERNAME: ${{ github.event.inputs.Username }}
  LABSTAR-PASSWORD: ${{ github.event.inputs.Password }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: enviorment vars
        run: |
          echo "url: ${{ env.LABSTAR-URL }}" 
          echo "username: ${{ env.LABSTAR-USERNAME }}"
          echo "password: ${{ env.LABSTAR-PASSWORD }}"
      
      - name: show inputs
        run: |
          echo "url: ${{ github.event.inputs.Url }}" 
          echo "username: ${{ github.event.inputs.Username }}"
          echo "password: ${{ github.event.inputs.Password }}"
          
          
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Thundra Maven Test Instrumentation
        uses: thundra-io/thundra-maven-test-action@v1
        with:
          apikey: f63aa2c7-7ea0-4b28-9472-ffd6d1e7d33b
          project_id: c4a40144-6b41-4edc-b64e-475a59accb7a
          command: mvn clean install
