# This is a basic workflow to help you get started with Actions

name: CI

env:
  labstar-url: 'https://preview-ng.labstar.com/'
  labstar-username: user1
  labstar-password: pass

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]
  
  workflow_dispatch:
     inputs:
      Url:
        description: 'Url'     
        required: true
        default: ${{ env.labstar-url }} 
      Username:
        description: 'Username'     
        required: true
        default: $labstar-username
      Password:
        description: 'Password'     
        required: true
        default: $labstar-password

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "url: ${{ github.event.inputs.Url }}" 
          echo "username: ${{ github.event.inputs.Username }}"
          echo "password: ${{ github.event.inputs.Password }}"
