# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master ]
  workflow_dispatch:
     inputs:
      Url:
        description: 'Url'     
        required: true
        default: 'https://preview-ng.labstar.com/'
      Username:
        description: 'Username'     
        required: true
        default: 'support'
      Password:
        description: 'Password'     
        required: true
        default: 'eVxU6%wK9'
env:
 TestOptions__Headless: false
 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Replace env variable from input
        if: github.event.inputs.Url != ''
        env:
          SiteOptions__Url : ${{ github.event.inputs.Url }}
          SiteOptions__Username : ${{ github.event.inputs.Username }}
          SiteOptions__Password : ${{ github.event.inputs.Password }}
        run: |
          echo "url: ${{ env.SiteOptions__Url }}" 
          echo "username: ${{ env.SiteOptions__Username }}"
          echo "password: ${{ env.SiteOptions__Password }}"
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: enviorment vars
        run: |
          echo "url: ${{ env.SiteOptions__Url }}" 
          echo "username: ${{ env.SiteOptions__Username }}"
          echo "password: ${{ env.SiteOptions__Password }}"
      
      - name: show inputs
        run: |
          echo "url: ${{ github.event.inputs.Url }}" 
          echo "username: ${{ github.event.inputs.Username }}"
          echo "password: ${{ github.event.inputs.Password }}"
          
          
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-results/**/*.xml
